apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: malachowski-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hhh.mzylowski.pl
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
